baseURL = "https://davoodharun.github.io/blog/"
languageCode = "en-us"
title = "Harun Davood"

[params]
  description = "A personal blog featuring writing, music, and visual design work"
  author = "Your Name"
  github = "davoodharun"
  
[menu]
  [[menu.main]]
    identifier = "writing"
    name = "Writing"
    url = "/writing/"
    weight = 1
  [[menu.main]]
    identifier = "music"
    name = "Music"
    url = "/music/"
    weight = 2
  [[menu.main]]
    identifier = "visual"
    name = "Visual Work"
    url = "/visual/"
    weight = 3

[params.social]
  soundcloud = "harun-davood"
  instagram = "davoodharun"

[taxonomies]
  tag = "tags"
  category = "categories"


